name: Workflow
on: [push]

jobs: 
  buildAndTest:
    runs-on: windows-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: nanasess/setup-php@master
      - uses: nanasess/setup-chromedriver@master
      - name: Install dependecies
        run: composer install
      - name: Install Webdriver
        run: composer require --dev codeception/module-webdriver
      - name: Install faker
        run: composer require fakerphp/faker
      - name: Run chromedriver
        run: 
           chromedriver --url-base=/wd/hub &
      - name: Install Rest
        run: composer require --dev codeception/module-rest
      - name: Run tests
        run: php vendor/bin/codecept run --steps -vvv --xml
      - name: JUnit Report Action
        if: always()
        uses: mikepenz/action-junit-report@v2.4.2
        with:
          report_paths: 'tests/_output/report.xml'
      




